// https://adventofcode.com/2025/day/7

public static class Program
{
    static void PerformTests()
    {
        string testData = @".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............";

        
    }

    static void PerformPuzzleOne()
    {

    }
    
    static void PerformPuzzleTwo()
    {
        
    }

    public static void Main(string[] args)
    {
        
    }
}